# This file is used to deploy the backend service to the cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-deployment # This is the label of the deployment
spec:
  selector:
    matchLabels:
      app: golang-backend # This is the label of the deployment where the pod will be deployed
  replicas: 1
  template:
    metadata:
      labels:
        app: golang-backend
    spec:
      containers:
        - name: golang-container
          image: quay.io/mahermahmoudsafwat/backend_image:latest
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: DB_HOST
              value: 172.30.128.160 #this is the name of the service that we created earlier
            - name: DB_PORT
              value: 3306
          ports:
            - containerPort: 8080
---
# expose the backend service to the outside world
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  selector:
    app: golang-backend
  ports:
    - protocol: TCP
      port: 8080 # This is the port that the service will listen on inside the cluster
      targetPort: 8080 # This is the port that the service will be exposed on outside the cluster
  type: NodePort
